# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='review_id',
        ),
        migrations.AddField(
            model_name='reviews',
            name='book_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reviews.books'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='Reviews.users'),
        ),
    ]
